var searchData=
[
  ['scheduler_0',['Releasing the scheduler',['../q_foundations.html#q_releasescheduler',1,'']]],
  ['scheduler_20interface_1',['Scheduler Interface',['../group__qtaskcreation.html',1,'']]],
  ['scheduling_2',['A simple scheduling',['../q_gettingstarted.html#q_os_example1',1,'']]],
  ['scheduling_20rules_3',['Global states and scheduling rules',['../q_foundations.html#q_globalstates',1,'']]],
  ['scheme_4',['Adding tasks to the scheme',['../q_foundations.html#q_addtasks',1,'']]],
  ['sections_5',['Critical sections',['../q_foundations.html#q_critical',1,'']]],
  ['semaphores_6',['Semaphores',['../q_qcoroutines.html#q_coroutine_semaphores',1,'']]],
  ['semaphores_7',['Co-Routine example with semaphores.',['../q_qcoroutines.html#q_coroutine_example2',1,'']]],
  ['sending_20notifications_8',['Sending notifications',['../q_events.html#q_notificationsend',1,'']]],
  ['sending_20signals_9',['Sending signals',['../q_fsm.html#q_fsmsendsignals',1,'']]],
  ['setting_20up_20a_20queue_10',['Setting up a queue',['../q_events.html#q_queuesetup',1,'']]],
  ['setting_20up_20a_20state_20machine_11',['Setting up a state machine',['../q_fsm.html#q_fsmsetup',1,'']]],
  ['setting_20up_20an_20at_20cli_20instance_12',['Setting up an AT-CLI instance',['../q_atcli.html#q_atcli_setup',1,'']]],
  ['sigdata_13',['sigData',['../structq_s_m___signal__t.html#a868ff63ba89752ded52f670ee830b57c',1,'qSM_Signal_t']]],
  ['signal_14',['Signal',['../structq_s_m___handler__t.html#a185fb13f4184b5f4cc05b01059e31964',1,'qSM_Handler_t']]],
  ['signal_20actions_20and_20guards_15',['Signal actions and guards',['../q_fsm.html#q_fsm_sigactions',1,'']]],
  ['signal_20queue_16',['Installing a signal queue',['../q_fsm.html#q_fsminstallsignalqueue',1,'']]],
  ['signaldata_17',['SignalData',['../structq_s_m___handler__t.html#a57bd1782dce058f1af8d9ac429ae8e7c',1,'qSM_Handler_t']]],
  ['signaldata_18',['signalData',['../structq_s_m___transition__t.html#a1d558129fce0870a2746d3aafce08726',1,'qSM_Transition_t']]],
  ['signals_19',['Sending signals',['../q_fsm.html#q_fsmsendsignals',1,'']]],
  ['simple_20demonstrative_20examples_20',['Two simple demonstrative examples',['../q_gettingstarted.html#q_os_demo',1,'']]],
  ['simple_20notifications_21',['Simple Notifications',['../q_events.html#q_simplenot',1,'']]],
  ['simple_20scheduling_22',['A simple scheduling',['../q_gettingstarted.html#q_os_example1',1,'']]],
  ['sized_20buffers_23',['Byte-Sized buffers',['../group__qbsbuffers.html',1,'']]],
  ['software_20timers_24',['Software-Timers',['../group__qstimers.html',1,'']]],
  ['specification_25',['FSM Timeout specification',['../q_fsm.html#q_fsm_timeout',1,'']]],
  ['spread_20a_20notification_26',['Spread a notification',['../q_events.html#qnotspread',1,'']]],
  ['stage_27',['stage',['../structq_list___for_each_handle__t.html#a3a0029b84cc61be4b552d11e6770fb6f',1,'qList_ForEachHandle_t']]],
  ['standard_28',['Development process and coding standard',['../q_background.html#q_codstandard',1,'']]],
  ['startdelay_29',['StartDelay',['../structq_event__t.html#aee880e0bf7834b8ca68c2bcd6ddab532',1,'qEvent_t']]],
  ['started_30',['Getting started',['../q_gettingstarted.html',1,'']]],
  ['startstate_31',['StartState',['../structq_s_m___handler__t.html#a10e59c21e0e6763803fcb9f4414858ef',1,'qSM_Handler_t']]],
  ['state_32',['state',['../structq_s_m___handler__t.html#a4ab71110ab86b6df4d2a2edd3e5f9c2f',1,'qSM_Handler_t']]],
  ['state_20callback_20handler_3a_20performing_20transitions_20and_20retrieving_20data_33',['The state callback handler: performing transitions and retrieving data',['../q_fsm.html#q_fsmhandler',1,'']]],
  ['state_20machine_34',['Setting up a state machine',['../q_fsm.html#q_fsmsetup',1,'']]],
  ['state_20machine_20as_20a_20task_35',['Adding a state machine as a task',['../q_fsm.html#q_fsm_astask',1,'']]],
  ['state_20machines_36',['Finite State Machines',['../group__qfsm.html',1,'']]],
  ['state_20machines_20fsm_37',['Finite State Machines (FSM)',['../q_fsm.html',1,'q_extensions']]],
  ['statedata_38',['StateData',['../structq_s_m___handler__t.html#a1e16ba53a2dd6f04b0ce0d8ecf128542',1,'qSM_Handler_t']]],
  ['states_39',['states',['../q_foundations.html#q_os_operational_states',1,'Additional operational states'],['../q_fsm.html#q_fsm_example4',1,'Example with history pseudo-states']]],
  ['states_20and_20defining_20callbacks_40',['Subscribing states and defining callbacks',['../q_fsm.html#q_fsm_subscribe_states',1,'']]],
  ['states_20and_20scheduling_20rules_41',['Global states and scheduling rules',['../q_foundations.html#q_globalstates',1,'']]],
  ['status_42',['Status',['../structq_s_m___handler__t.html#a9a9b417b18be359dcef7d0c979db078a',1,'qSM_Handler_t']]],
  ['steps_43',['First steps',['../q_gettingstarted.html#q_firststeps',1,'']]],
  ['stimer_44',['Using a STimer',['../q_stimers.html#q_stimerusage',1,'']]],
  ['stimer_20example_45',['STimer example',['../q_stimers.html#q_stimerexample',1,'']]],
  ['stimers_46',['STimers',['../q_stimers.html',1,'q_extensions']]],
  ['strdata_47',['StrData',['../structq_a_t_c_l_i___handler__t.html#ad5fcdcc3a862a1907c088abf07aa30fe',1,'qATCLI_Handler_t']]],
  ['strlen_48',['StrLen',['../structq_a_t_c_l_i___handler__t.html#aa0d42278e492e50a660824c4b1ddaa7f',1,'qATCLI_Handler_t']]],
  ['sub_20module_49',['Including QuarkTS as a git sub-module',['../q_gettingstarted.html#q_submodule',1,'']]],
  ['subscribing_20commands_20to_20the_20parser_50',['Subscribing commands to the parser',['../q_atcli.html#q_atcli_sub_commands',1,'']]],
  ['subscribing_20states_20and_20defining_20callbacks_51',['Subscribing states and defining callbacks',['../q_fsm.html#q_fsm_subscribe_states',1,'']]],
  ['supported_20syntax_52',['Supported syntax',['../q_atcli.html#q_atcli_syntax',1,'']]],
  ['surrounding_20callback_53',['The surrounding callback',['../q_fsm.html#q_fsm_surrounding',1,'']]],
  ['syntax_54',['Supported syntax',['../q_atcli.html#q_atcli_syntax',1,'']]],
  ['system_55',['Operative System',['../group__qos.html',1,'']]]
];
