var searchData=
[
  ['table_0',['Using a transition table',['../q_fsm.html#q_fsm_ttable',1,'']]],
  ['tables_1',['Demonstrative example using transition tables',['../q_fsm.html#q_fsm_example2',1,'']]],
  ['task_2',['task',['../q_fsm.html#q_fsm_astask',1,'Adding a state machine as a task'],['../q_events.html#q_attachqueue',1,'Attach a queue to a task'],['../q_foundations.html#q_removetask',1,'Removing a task'],['../q_foundations.html#q_idletask',1,'The idle task']]],
  ['task_20argument_3',['Using the task argument',['../q_gettingstarted.html#q_os_example2',1,'']]],
  ['task_20communication_4',['Inter-Task communication',['../group__qpriv.html',1,'']]],
  ['task_20communication_5',['Asynchronous events and inter-task communication',['../q_events.html#q_asyncevents',1,'']]],
  ['task_20event_20flags_6',['Using the task Event-flags',['../q_events.html#q_eventflagsexample',1,'']]],
  ['taskdata_7',['TaskData',['../structq_event__t.html#a191262c05958798bbb47391043170b2a',1,'qEvent_t']]],
  ['tasks_8',['Tasks',['../q_foundations.html#q_tasks',1,'']]],
  ['tasks_9',['tasks',['../q_foundations.html#q_eventtasks',1,'Event-triggered tasks'],['../group__qtaskmanip.html',1,'Managing tasks']]],
  ['tasks_20to_20the_20scheme_10',['Adding tasks to the scheme',['../q_foundations.html#q_addtasks',1,'']]],
  ['text_11',['Text',['../structq_a_t_c_l_i___command__t.html#a47d78e3fdac68cc14477265ae43253d6',1,'qATCLI_Command_t']]],
  ['the_20cli_12',['The components of the CLI',['../q_atcli.html#q_atcli_components',1,'']]],
  ['the_20cli_20parser_13',['Running the CLI parser',['../q_atcli.html#q_atcli_run',1,'']]],
  ['the_20components_20of_20the_20cli_14',['The components of the CLI',['../q_atcli.html#q_atcli_components',1,'']]],
  ['the_20event_20data_15',['Retrieving the event data',['../q_events.html#eventdata',1,'']]],
  ['the_20hierarchical_20approach_16',['Using the hierarchical approach',['../q_fsm.html#qfsm_happroach',1,'']]],
  ['the_20idle_20task_17',['The idle task',['../q_foundations.html#q_idletask',1,'']]],
  ['the_20input_18',['Handling the input',['../q_atcli.html#q_atcli_inputh',1,'']]],
  ['the_20os_19',['the OS',['../q_background.html#q_about',1,'About the OS'],['../q_gettingstarted.html#q_getos',1,'Getting the OS'],['../q_foundations.html#q_runos',1,'Running the OS']]],
  ['the_20os_20configuration_20file_20',['Get a copy of the OS configuration file',['../q_gettingstarted.html#q_getqconfig',1,'']]],
  ['the_20parser_21',['Subscribing commands to the parser',['../q_atcli.html#q_atcli_sub_commands',1,'']]],
  ['the_20provided_20approach_22',['The provided approach',['../q_fsm.html#qfsm_approach',1,'']]],
  ['the_20scheduler_23',['Releasing the scheduler',['../q_foundations.html#q_releasescheduler',1,'']]],
  ['the_20scheme_24',['Adding tasks to the scheme',['../q_foundations.html#q_addtasks',1,'']]],
  ['the_20state_20callback_20handler_3a_20performing_20transitions_20and_20retrieving_20data_25',['The state callback handler: performing transitions and retrieving data',['../q_fsm.html#q_fsmhandler',1,'']]],
  ['the_20surrounding_20callback_26',['The surrounding callback',['../q_fsm.html#q_fsm_surrounding',1,'']]],
  ['the_20task_20argument_27',['Using the task argument',['../q_gettingstarted.html#q_os_example2',1,'']]],
  ['the_20task_20event_20flags_28',['Using the task Event-flags',['../q_events.html#q_eventflagsexample',1,'']]],
  ['the_20time_20elapsed_20event_29',['The Time-Elapsed event',['../q_events.html#q_event_timeelapsed',1,'']]],
  ['time_20elapsed_20event_30',['The Time-Elapsed event',['../q_events.html#q_event_timeelapsed',1,'']]],
  ['timeout_20specification_31',['FSM Timeout specification',['../q_fsm.html#q_fsm_timeout',1,'']]],
  ['timers_32',['Software-Timers',['../group__qstimers.html',1,'']]],
  ['timing_20approach_33',['Timing Approach',['../q_foundations.html#q_timmingapproach',1,'']]],
  ['to_20a_20task_34',['Attach a queue to a task',['../q_events.html#q_attachqueue',1,'']]],
  ['to_20completion_20model_35',['RTC(Run To Completion) model',['../q_foundations.html#rtcmodel',1,'']]],
  ['to_20the_20parser_36',['Subscribing commands to the parser',['../q_atcli.html#q_atcli_sub_commands',1,'']]],
  ['to_20the_20scheme_37',['Adding tasks to the scheme',['../q_foundations.html#q_addtasks',1,'']]],
  ['trace_38',['Trace',['../group__qtrace.html',1,'']]],
  ['trace_20debugging_39',['Trace/Debugging',['../q_trace.html',1,'q_extensions']]],
  ['transition_20table_40',['Using a transition table',['../q_fsm.html#q_fsm_ttable',1,'']]],
  ['transition_20tables_41',['Demonstrative example using transition tables',['../q_fsm.html#q_fsm_example2',1,'']]],
  ['transitionhistory_42',['TransitionHistory',['../structq_s_m___handler__t.html#acde5467a47c845d8f84629204ffb0a9d',1,'qSM_Handler_t']]],
  ['transitions_20and_20retrieving_20data_43',['The state callback handler: performing transitions and retrieving data',['../q_fsm.html#q_fsmhandler',1,'']]],
  ['trigger_44',['Trigger',['../structq_event__t.html#a61ae4900215e528bd801c8ee156ac0df',1,'qEvent_t']]],
  ['triggered_20tasks_45',['Event-triggered tasks',['../q_foundations.html#q_eventtasks',1,'']]],
  ['two_20simple_20demonstrative_20examples_46',['Two simple demonstrative examples',['../q_gettingstarted.html#q_os_demo',1,'']]],
  ['type_47',['Type',['../structq_a_t_c_l_i___handler__t.html#ace2594f0621470e85de85c9c5ee9c06d',1,'qATCLI_Handler_t']]],
  ['types_20and_20macros_48',['Types and macros',['../group__qtypes.html',1,'']]]
];
