var searchData=
[
  ['callback_0',['callback',['../q_fsm.html#q_fsm_surrounding',1,'The surrounding callback'],['../q_atcli.html#q_atcli_cmd_callback',1,'Writing a command callback']]],
  ['callback_20handler_3a_20performing_20transitions_20and_20retrieving_20data_1',['The state callback handler: performing transitions and retrieving data',['../q_fsm.html#q_fsmhandler',1,'']]],
  ['callbacks_2',['Subscribing states and defining callbacks',['../q_fsm.html#q_fsm_subscribe_states',1,'']]],
  ['calls_20in_20a_20co_20routine_3',['Blocking calls in a Co-routine',['../q_qcoroutines.html#q_coroutine_blocking',1,'']]],
  ['checking_4',['I/O Groups for edge checking',['../group__qedgecheck.html',1,'']]],
  ['cli_5',['CLI',['../q_atcli.html',1,'AT Command Line Interface (CLI)'],['../q_atcli.html#q_atcli_components',1,'The components of the CLI']]],
  ['cli_20example_6',['A CLI example',['../q_atcli.html#q_atcli_example1',1,'']]],
  ['cli_20instance_7',['Setting up an AT-CLI instance',['../q_atcli.html#q_atcli_setup',1,'']]],
  ['cli_20parser_8',['Running the CLI parser',['../q_atcli.html#q_atcli_run',1,'']]],
  ['clock_9',['Clock',['../group__qclock.html',1,'']]],
  ['cloning_20quarkts_10',['Cloning QuarkTS',['../q_gettingstarted.html#q_cloneos',1,'']]],
  ['co_20routine_11',['Coding a Co-Routine',['../q_qcoroutines.html#q_coroutine_code',1,'']]],
  ['co_20routine_12',['Blocking calls in a Co-routine',['../q_qcoroutines.html#q_coroutine_blocking',1,'']]],
  ['co_20routine_20example_20with_20semaphores_13',['Co-Routine example with semaphores.',['../q_qcoroutines.html#q_coroutine_example2',1,'']]],
  ['co_20routine_20usage_20example_14',['Co-Routine usage example',['../q_qcoroutines.html#q_coroutine_example1',1,'']]],
  ['co_20routines_15',['Co Routines',['../group__qcoroutines.html',1,'Co-Routines'],['../q_qcoroutines.html',1,'Co-Routines']]],
  ['coding_20a_20co_20routine_16',['Coding a Co-Routine',['../q_qcoroutines.html#q_coroutine_code',1,'']]],
  ['coding_20standard_17',['Development process and coding standard',['../q_background.html#q_codstandard',1,'']]],
  ['command_18',['Command',['../structq_a_t_c_l_i___handler__t.html#aa4dad4783e4d65b4cb04e96e3ccc8ed5',1,'qATCLI_Handler_t']]],
  ['command_20callback_19',['Writing a command callback',['../q_atcli.html#q_atcli_cmd_callback',1,'']]],
  ['command_20line_20interface_20',['AT Command Line Interface',['../group__qatcli.html',1,'']]],
  ['command_20line_20interface_20cli_21',['AT Command Line Interface (CLI)',['../q_atcli.html',1,'q_extensions']]],
  ['commands_20to_20the_20parser_22',['Subscribing commands to the parser',['../q_atcli.html#q_atcli_sub_commands',1,'']]],
  ['communication_23',['communication',['../q_events.html#q_asyncevents',1,'Asynchronous events and inter-task communication'],['../group__qpriv.html',1,'Inter-Task communication']]],
  ['compatibility_24',['Hardware compatibility',['../q_background.html#q_hardwarecompatibility',1,'']]],
  ['completion_20model_25',['RTC(Run To Completion) model',['../q_foundations.html#rtcmodel',1,'']]],
  ['components_20of_20the_20cli_26',['The components of the CLI',['../q_atcli.html#q_atcli_components',1,'']]],
  ['configuration_20file_27',['Get a copy of the OS configuration file',['../q_gettingstarted.html#q_getqconfig',1,'']]],
  ['configuration_20macros_28',['Configuration macros',['../q_foundations.html#q_configmacros',1,'']]],
  ['control_29',['External control',['../q_qcoroutines.html#q_coroutine_ext',1,'']]],
  ['copy_20of_20the_20os_20configuration_20file_30',['Get a copy of the OS configuration file',['../q_gettingstarted.html#q_getqconfig',1,'']]],
  ['critical_31',['Critical',['../group__qcritical.html',1,'']]],
  ['critical_20sections_32',['Critical sections',['../q_foundations.html#q_critical',1,'']]]
];
