name: Static-Analisys

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - name: Update OS packages list
      run: |
        sudo apt-get update -yq 
    - name: Install analyzer
      run: |
        sudo apt-get install -y cppcheck python3
        mkdir sa_results
    - name: General checks 
      run: cppcheck --enable=all --inline-suppr --inconclusive --std=c99 ./src/os -I ./src/os/include --output-file=./sa_results/general.txt --suppress=missingIncludeSystem 
    - name: CERT checks 
      run: cppcheck --addon=cert.py --inline-suppr --inconclusive --std=c99 ./src/os -I ./src/os/include --output-file=./sa_results/cert.txt --suppress=missingIncludeSystem
    - name: MISRA checks 
      run: cppcheck --addon=./check/misra.json --inline-suppr --inconclusive --std=c99 ./src/os -I ./src/os/include --output-file=./sa_results/misra.txt --suppress=missingIncludeSystem      
    - uses: actions/upload-artifact@v3
      with:
        name: Static_Analyses_Results
        path: sa_results