name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: create dirs
      run: mkdir docout
    - name: set repo url on corner
      run: sed -i 's,https://github.com/jothepro/doxygen-awesome-css,https://github.com/kmilo17pet/QuarkTS,g' doc/stylesheet/doxygen-custom/header.html
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        doxyfile-path: './doc/Doxygen'
    - name: rm gitignore
      run: rm .gitignore  
    - name: Deploy doc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doxyout/html
